# Generated by Django 5.0.6 on 2024-06-25 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_likedislike_user_alter_likedislike_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likedislike',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='likedislike',
            name='user',
        ),
    ]
